---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: release
spec:
  params:
    - name: releasePlan
      description: Namespaced name of release plan - should be in format "namespace/name"
      type: string
    - name: snapshot
      description: Namespaced name of snapshot - should be in format "namespace/name"
      type: string
    - name: release
      description: Namespaced name of release - should be in format "namespace/name"
      type: string
  tasks:
    - name: release
      taskSpec:
        steps:
          - name: check-release-status
            image: quay.io/konflux-ci/release-service-utils:066a63d25546239e79533b99c83ff521a045c819
            script: |
              #!/usr/bin/env bash
              set -eux

              # check for release status and check if a managed pipeline failed
              IFS='/' read -r RELEASE_NAMESPACE RELEASE_NAME <<< "$(params.release)"
              RELEASECONDITIONS=$(kubectl get release "$RELEASE_NAME" -n "$RELEASE_NAMESPACE" \
                -o jsonpath='{.status.conditions}')
              if [ -z "$RELEASECONDITIONS" ]; then
                echo "No release conditions found for $RELEASE_NAME in namespace $RELEASE_NAMESPACE"
                exit 1
              fi

              RELEASECONDITION=$(echo "$RELEASECONDITIONS" | jq '.[] | select(.type == "ManagedPipelineProcessed")')
              RELEASESTATUS=$(jq -r '.reason' <<< "$RELEASECONDITION")
              echo "Release status: $RELEASESTATUS"

              if [[ "$RELEASESTATUS" != *"Succeeded"* ]]; then
                echo "Release did not succeed, stopping snapshot push"
                exit 1
              fi
